sonar.projectKey=abdulraheem1308_Wellnex_app
sonar.organization=abdulraheem1308
sonar.projectName=Wellnex Frontend
sonar.projectVersion=1.0.0

# Path to source directories (required)
sonar.sources=lib

# Exclude generated and test files from code analysis
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**,lib/l10n/**

# Path to test directories
sonar.tests=test

# Coverage reports
sonar.dart.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

# Quality Gates
sonar.qualitygate.wait=true
